/**
 * GENERATED by scripts/gen-wordmark.mjs — do not edit by hand.
 *
 * Where every letter of the wordmark sits inside the 657x268 artwork,
 * measured off its alpha channel, plus the typographic rules each line sits on.
 * The reveal draws one letter at a time and needs a box per letter to sweep
 * down; the blueprint stage draws the rules.
 */
export const LOGO_BOX = { width: 657, height: 268 } as const;

export type GlyphBox = {
  glyph: string;
  line: number;
  x: number;
  y: number;
  w: number;
  h: number;
};

export const GLYPHS: readonly GlyphBox[] = [
  { glyph: "M", line: 0, x: 51, y: 13, w: 121, h: 114 },
  { glyph: "i", line: 0, x: 190, y: 8, w: 28, h: 119 },
  { glyph: "l", line: 0, x: 235, y: 12, w: 23, h: 115 },
  { glyph: "a", line: 0, x: 273, y: 42, w: 77, h: 86 },
  { glyph: "g", line: 0, x: 364, y: 42, w: 84, h: 118 },
  { glyph: "r", line: 0, x: 466, y: 42, w: 52, h: 85 },
  { glyph: "o", line: 0, x: 523, y: 42, w: 85, h: 86 },
  { glyph: "u", line: 1, x: 8, y: 176, w: 79, h: 84 },
  { glyph: "n", line: 1, x: 106, y: 174, w: 79, h: 84 },
  { glyph: "i", line: 1, x: 202, y: 139, w: 27, h: 119 },
  { glyph: "v", line: 1, x: 238, y: 176, w: 89, h: 82 },
  { glyph: "e", line: 1, x: 331, y: 174, w: 83, h: 86 },
  { glyph: "r", line: 1, x: 428, y: 174, w: 51, h: 84 },
  { glyph: "s", line: 1, x: 484, y: 174, w: 73, h: 86 },
  { glyph: "e", line: 1, x: 566, y: 174, w: 83, h: 86 },
];

export type LineGuide = {
  line: number;
  left: number;
  right: number;
  ascender: number;
  xHeight: number;
  baseline: number;
  descender: number;
};

export const GUIDES: readonly LineGuide[] = [
  { line: 0, left: 51, right: 608, ascender: 8, xHeight: 42, baseline: 127, descender: 160 },
  { line: 1, left: 8, right: 649, ascender: 139, xHeight: 174, baseline: 258, descender: 260 },
];
